version: '3.8'

services:
  api:
    build:
      context: .            # IMPORTANT: Must be root so both api/ and client/ are accessible
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
networks:
  app-network:
    driver: bridge
